- name: Copy Mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present


- name: Updating mongodb config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: 127.0.0.1 
    replace: 0.0.0.0 

- name: Start Mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: true

- name: Download and extracting
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Load catalogue schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users
