- name: Configuring Nodejs repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install Nodejs
  ansible.builtin.package:
    name: nodejs
    state: present 

- name: Creating the application user account 
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: Roboshop service account

- name: Download and extracting the Component
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Cleanup of old content
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent

- name: Copy files to roboshop homedir
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    remote_src: yes
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"

- name: Installing nodejs package
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Copy systemd service file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service
